### PR TITLE
Add (de-)serialization to data store

### PR DESCRIPTION
**Pull request by saulshanabrook**

### CODE REVIEW

**Comment by ian-r-rose** [comment]
I'd rather not have these commits in here for now. I have this branch open as a PR with no API changes against `feature-tables-3`.

**Comment by saulshanabrook** [comment]
OK I reverted these changed https://github.com/ian-r-rose/phosphor/pull/4. I need a working branch to base the JupyterLab work off of, I will just create one in my own fork then and merge your work in to that as well as this. For some reason I was unable to create a PR from vidar's branch against the main `feature-tables3` branch, "Pull request creation failed. Validation failed: You can't perform that action at this time."

**Comment by ian-r-rose** [comment]
Weird. Sorry for the confusion -- I was hoping to get this into the main `feature-tables3` branch before doing any major API changes.

**Comment by saulshanabrook** [comment]
Yep, that makes sense! Sorry for confusion too.

**Pull request merged**
